language: node_js
node_js:
- "6"
sudo: false 
dist: trusty
addons:
 apt:
   sources:
     - google-chrome
   packages:
     - google-chrome-stable

before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - set -x
  - scripts/get_geckdriver.sh 
  - scripts/get_selenium.sh 
  - scripts/get_chromedriver.sh 
  - scripts/connect3.sh &
  - echo "check to see selenum running"
  - echo `ps -aef |grep selenium`
  - node tests/jsunit/test_runner.js

os:
  - linux 
