language: node_js
node_js:
- "stable"

matrix:
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - google-chrome-stable
  - os: osx
    osx_image: xcode8.3

before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( sh -e /etc/init.d/xvfb start; export CHROME_BIN="/usr/bin/google-chrome" )& fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( scripts/setup_osx.sh ) fi
  - sleep 2 

script:
  - set -x
  - npm test
