language: node_js
node_js:
- "stable"
sudo: required
dist: trusty
addons:
 apt:
   packages:
     - google-chrome-stable

before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( sh -e /etc/init.d/xvfb start; export CHROME_BIN="/usr/bin/google-chrome" )& fi
  - scripts/setup_osx.sh
  - sleep 2 

script:
  - set -x
  - npm test

os:
  - linux 
  - osx
