language: node_js
node_js:
- "stable"
sudo: required
dist: trusty
addons:
 apt:
   sources:
     - google-chrome
   packages:
     - google-chrome-stable
     - freeglut3-dev
     - xutils-dev
     - libxi-dev
     - libxxf86vm-dev
     - x11proto-xf86vidmode-dev
     - mesa-utils
     - xvfb
     - libgl1-mesa-dri
     - libglapi-mesa
     - libosmesa6

before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library



before_script:
  - export DISPLAY=:99.0
  - echo "osname is ${TRAVIS_OS_NAME}"
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( sh -e /etc/init.d/xvfb start )& fi
  - brew cask install google-chrome
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo okkkkkkkkkkkkkk )& fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( export CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ) fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( export CHROME_BIN="/usr/bin/google-chrome" ) fi
#  - \"$CHROME_BIN\" --version
  - echo "chrome path is ${CHROME_BIN}"
  - sleep 3

script:
  - set -x
  - npm test

os:
  - linux
